# Generated by Django 3.1.3 on 2020-11-23 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCoordinate',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True)),
                ('longititude', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rentproperty',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rent', models.FloatField(blank=True, null=True)),
                ('kanrihi', models.FloatField(blank=True, null=True)),
                ('sikikin', models.FloatField(blank=True, null=True)),
                ('reikin', models.FloatField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longititude', models.FloatField(blank=True, null=True)),
                ('close_station', models.IntegerField(blank=True, null=True)),
                ('floor_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=5, null=True)),
                ('bath_toilet', models.BooleanField(blank=True, null=True)),
                ('auto_lock', models.BooleanField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('predicted_rent', models.FloatField(blank=True, null=True)),
                ('rent_diff', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'url')},
            },
        ),
    ]
