# Generated by Django 3.1.3 on 2020-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCoordinate',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True)),
                ('longititude', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rent', models.FloatField()),
                ('max_rent', models.FloatField()),
                ('floor_plan', models.CharField(choices=[('ワンルーム', 'ワンルーム'), ('1K', '1K'), ('1DK', '1DK'), ('1LDK', '1LDK'), ('2LDK', '2LDK'), ('3LDK', '3LDK')], max_length=10)),
                ('min_area', models.CharField(choices=[('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50')], max_length=10)),
                ('bath_toilet', models.CharField(choices=[('バストイレ別', 'バストイレ別'), ('ユニットバス', 'ユニットバス')], max_length=10)),
                ('autolock', models.CharField(choices=[('オートロック有り', 'オートロック有り'), ('オートロックなし', 'オートロックなし')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rentproperty',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('rent', models.FloatField(blank=True, null=True)),
                ('kanrihi', models.FloatField(blank=True, null=True)),
                ('sikikin', models.FloatField(blank=True, null=True)),
                ('reikin', models.FloatField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longititude', models.FloatField(blank=True, null=True)),
                ('close_station', models.IntegerField(blank=True, null=True)),
                ('floor_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=5, null=True)),
                ('bath_toilet', models.BooleanField(blank=True, null=True)),
                ('auto_lock', models.BooleanField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('predicted_rent', models.FloatField(blank=True, null=True)),
                ('rent_diff', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'url')},
            },
        ),
    ]
